name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    strategy:
      matrix:
        ruby:
          - '3.1.2'
          - '3.3'
        rails:
          - '7.0'
          - '7.1'
          - '8.0'
          - '8.1'
        exclude:
          # Rails 8.1 requires Ruby >= 3.2.0
          - ruby: '3.1.2'
            rails: '8.1'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
      env:
        RAILS_VERSION: ${{ matrix.rails }}
    - name: Run the default task
      run: bundle exec rake
      env:
        RAILS_VERSION: ${{ matrix.rails }}
