name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    strategy:
      matrix:
        include:
          - ruby: '3.2'
            rails: '7.1'
          - ruby: '3.2'
            rails: '8.0'
          - ruby: '3.3'
            rails: '8.1'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
      env:
        RAILS_VERSION: ${{ matrix.rails }}
    - name: Run the default task
      run: bundle exec rake
      env:
        RAILS_VERSION: ${{ matrix.rails }}
