name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g. 1.2.3 or v1.2.3)"
        required: true
        type: string
      prerelease:
        description: "Mark release as pre-release"
        required: false
        default: false
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Fetch tags
        run: git fetch --tags

      - name: Prepare tag name
        id: prep
        run: |
          VERSION="${{ inputs.version }}"
          if [[ "$VERSION" == v* ]]; then
            TAG="$VERSION"
          else
            TAG="v$VERSION"
          fi
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Ensure tag does not already exist
        run: |
          if git rev-parse "${{ steps.prep.outputs.tag }}" >/dev/null 2>&1; then
            echo "Tag ${{ steps.prep.outputs.tag }} already exists" >&2
            exit 1
          fi

      - name: Create and push tag
        env:
          TAG_NAME: ${{ steps.prep.outputs.tag }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"

      - name: Create GitHub release with generated notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ steps.prep.outputs.tag }}
        run: |
          FLAGS=()
          if [[ "${{ inputs.prerelease }}" == 'true' ]]; then
            FLAGS+=("--prerelease")
          fi
          gh release create "$TAG_NAME" --generate-notes "${FLAGS[@]}"
